### ISSUE TITLE
Getting error while setting variable in configuration

### ISSUE THREAD

**Issue by mr-oz-09** [Eernie/StashBranchParametersPlugin#7]
I am getting a JSON error when setting my variables. 

Name:Branch
Branch Specifier (blank for 'any')  $Branch or ${Branch} doesnt seem to work.

I keep getting this error in the log "Caused by: net.sf.json.JSONException: A JSONObject text must begin with '{' at character 1 of " 

Any idea what the issue is?

**Comment by Eernie** [comment]
Can you provide some more information?
What version of the plugin do you use and what version of Jenkins?

Can you maybe supply a config.xml of the job? :)

**Comment by mr-oz-09** [comment]
jenkins 1.631 and plugin .20. I just installed the plugin yesterday.

**Comment by Eernie** [comment]
Does the exception occur while saving or executing?

**Comment by mr-oz-09** [comment]
saving, when i open up the job the exception happens .

**Comment by mr-oz-09** [comment]
w/o this plugin the job runs fine as this is a mere copy of what i already have. I would kust like the option ot have the drop down rather than copying and pasting my branch

**Comment by Eernie** [comment]
Maybe its conflicting with an plugin or something. Can you maybe give snipets of the config or something? This really confuses me.

**Comment by Eernie** [comment]
This was a problem with configuration.
