### ISSUE TITLE
No recent release on jenkinsci fork

### ISSUE THREAD

**Issue by StrangelyTyped** [Eernie/StashBranchParametersPlugin#9]
Sorry for opening this here but the owner of this repo appears to still be the owner of the [jenkinsci/stash-branch-parameters-plugin](https://github.com/jenkinsci/stash-branch-parameters-plugin) fork and there's no issue tracker on the fork. 

There has been no release of that plugin since December 2015, meaning that while PRs 7, 8, 10, 11, and 12 have been merged, they are not available in the version of the plugin on the jenkins update sites. Of particular concern is PR 12 which removes the 1000 entry limit on all API calls.

Is there any chance of getting a new release pushed out with the latest batch of changes please?

Thanks
Stewart A

**Comment by Eernie** [comment]
Thanks for this issue. To be honest, I had totally forgotten this plug in. For now I release the master as is. In 8 hours it will be upgradable.
